import Header from "./components/header";
import { ThemeProvider } from "next-themes";
import { TrackProvider } from "../context/trackContext";
export const metadata = {
  title: "door.link",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="light">
          <TrackProvider>
            <main className="max-w-7xl mx-auto bg-white dark:bg-[#121212] pb-10">
              <Header />
              {children}
            </main>
          </TrackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
